In [1]:
import numpy as np

In [2]:
w1 = np.array([[1,0.5,0.3,0.1,0.1],[0.5,1,0.4,0.1,0.1],[0.3,0.4,1,0.3,0.3],[0.1,0.1,0.3,1,0.5],[0.1,0.1,0.3,0.5,1]])
w2 = np.array([[1,0.2,0.5,0.1,0.1],[0.2,1,0.3,0.1,0.1],[0.5,0.3,1,0.3,0.3],[0.1,0.1,0.3,1,0.5],[0.1,0.1,0.3,0.5,1]])

In [3]:
eta = 10**(-6)

In [4]:
w1

array([[1. , 0.5, 0.3, 0.1, 0.1],
       [0.5, 1. , 0.4, 0.1, 0.1],
       [0.3, 0.4, 1. , 0.3, 0.3],
       [0.1, 0.1, 0.3, 1. , 0.5],
       [0.1, 0.1, 0.3, 0.5, 1. ]])

In [5]:
def p(w):
    x_dim = w.shape[0]
    y_dim = w.shape[1]
    p1 = np.zeros((x_dim,y_dim))
    for i in np.arange(p1.shape[0]):
        for j in np.arange(p1.shape[1]):
            a = np.ma.array(w[i,:], mask=False)
            a.mask[i] = True
            if i == j:
                p1[i,j] = 0.5
            else: 
                p1[i,j] = w[i,j]/(2*a.sum())
                
    return p1
        
    
def s(w, k):
    x_dim = w.shape[0]
    y_dim = w.shape[1]
    s = np.zeros((x_dim, y_dim))
    for i in np.arange(s.shape[0]):
        idx = np.argsort(w[i, :])[::-1][:k]
        for j in np.arange(s.shape[1]):           
            if j in idx:
                s[i,j] = w[i,j]/np.sum(w[i, idx])
            else:
                s[i,j] = 0    
    return s

def update_p(p, s):
    p_plus = s*p*s.T
    return p_plus
            

In [6]:
w1

array([[1. , 0.5, 0.3, 0.1, 0.1],
       [0.5, 1. , 0.4, 0.1, 0.1],
       [0.3, 0.4, 1. , 0.3, 0.3],
       [0.1, 0.1, 0.3, 1. , 0.5],
       [0.1, 0.1, 0.3, 0.5, 1. ]])

In [7]:
s1 = s(w1, 2)
s2 = s(w2, 2)

In [20]:
s1

array([[0.66666667, 0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.66666667, 0.        , 0.        , 0.        ],
       [0.        , 0.28571429, 0.71428571, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.66666667, 0.33333333],
       [0.        , 0.        , 0.        , 0.33333333, 0.66666667]])

In [21]:
s2

array([[0.66666667, 0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.76923077, 0.23076923, 0.        , 0.        ],
       [0.33333333, 0.        , 0.66666667, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.66666667, 0.33333333],
       [0.        , 0.        , 0.        , 0.33333333, 0.66666667]])

In [8]:
p1_0 = p(w1)


In [9]:
p2_0 = p(w2)

In [10]:
p1_0

array([[0.5       , 0.25      , 0.15      , 0.05      , 0.05      ],
       [0.22727273, 0.5       , 0.18181818, 0.04545455, 0.04545455],
       [0.11538462, 0.15384615, 0.5       , 0.11538462, 0.11538462],
       [0.05      , 0.05      , 0.15      , 0.5       , 0.25      ],
       [0.05      , 0.05      , 0.15      , 0.25      , 0.5       ]])

In [11]:
p2_0

array([[0.5       , 0.11111111, 0.27777778, 0.05555556, 0.05555556],
       [0.14285714, 0.5       , 0.21428571, 0.07142857, 0.07142857],
       [0.17857143, 0.10714286, 0.5       , 0.10714286, 0.10714286],
       [0.05      , 0.05      , 0.15      , 0.5       , 0.25      ],
       [0.05      , 0.05      , 0.15      , 0.25      , 0.5       ]])

In [12]:
p1_1 = update_p(p1_0, s2)
p2_1 = update_p(p2_0, s1)

In [13]:
p1_1

array([[0.22222222, 0.        , 0.01666667, 0.        , 0.        ],
       [0.        , 0.29585799, 0.        , 0.        , 0.        ],
       [0.01282051, 0.        , 0.22222222, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])

In [14]:
p2_1

array([[0.22222222, 0.01234568, 0.        , 0.        , 0.        ],
       [0.01587302, 0.22222222, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.25510204, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])

In [15]:
pc = (p2_1 + p1_1)/2

In [16]:
pc

array([[0.22222222, 0.00617284, 0.00833333, 0.        , 0.        ],
       [0.00793651, 0.25904011, 0.        , 0.        , 0.        ],
       [0.00641026, 0.        , 0.23866213, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])

In [17]:
p1_2 = update_p(p1_1, s2)
p2_2 = update_p(p2_1, s1)
p1_3 = update_p(p1_2, s2)
p2_3 = update_p(p2_2, s1)

In [18]:
pc_2 = (p2_2 + p1_2)/2
pc_2

array([[0.09876543, 0.00068587, 0.00092593, 0.        , 0.        ],
       [0.00088183, 0.13691467, 0.        , 0.        , 0.        ],
       [0.00071225, 0.        , 0.11445977, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.09876543, 0.00308642],
       [0.        , 0.        , 0.        , 0.00308642, 0.09876543]])

In [19]:
pc_3 = (p2_3 + p1_3)/2
pc_3

array([[4.38957476e-02, 7.62078951e-05, 1.02880658e-04, 0.00000000e+00,
        0.00000000e+00],
       [9.79815795e-05, 7.37419266e-02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [7.91389680e-05, 0.00000000e+00, 5.51504510e-02, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.38957476e-02,
        3.42935528e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.42935528e-04,
        4.38957476e-02]])