In [2]:
import numpy as np

In [3]:
w1 = np.array([[1,0.5,0.3,0.1,0.1],[0.5,1,0.4,0.1,0.1],[0.3,0.4,1,0.3,0.3],[0.1,0.1,0.3,1,0.5],[0.1,0.1,0.3,0.5,1]])
w2 = np.array([[1,0.2,0.5,0.1,0.1],[0.2,1,0.3,0.1,0.1],[0.5,0.3,1,0.3,0.3],[0.1,0.1,0.3,1,0.5],[0.1,0.1,0.3,0.5,1]])

In [48]:
eta = 10**(-6)

In [4]:
w1

array([[1. , 0.5, 0.3, 0.1, 0.1],
       [0.5, 1. , 0.4, 0.1, 0.1],
       [0.3, 0.4, 1. , 0.3, 0.3],
       [0.1, 0.1, 0.3, 1. , 0.5],
       [0.1, 0.1, 0.3, 0.5, 1. ]])

In [41]:
def p(w):
    x_dim = w.shape[0]
    y_dim = w.shape[1]
    p1 = np.zeros((x_dim,y_dim))
    for i in np.arange(p1.shape[0]):
        for j in np.arange(p1.shape[1]):
            a = np.ma.array(w[i,:], mask=False)
            a.mask[i] = True
            if i == j:
                p1[i,j] = 0.5
            else: 
                p1[i,j] = w[i,j]/(2*a.sum())
                
    return p1
        
    
def s(w, k):
    x_dim = w.shape[0]
    y_dim = w.shape[1]
    s = np.zeros((x_dim, y_dim))
    for i in np.arange(s.shape[0]):
        idx = np.argsort(w[i, :])[::-1][:k]
        for j in np.arange(s.shape[1]):           
            if j in idx:
                s[i,j] = w[i,j]/np.sum(w[i, idx])
            else:
                s[i,j] = 0    
    return s

def update_p(p, s):
    p_plus = s*p*s.T
    return p_plus
            

In [39]:
w1

array([[1. , 0.5, 0.3, 0.1, 0.1],
       [0.5, 1. , 0.4, 0.1, 0.1],
       [0.3, 0.4, 1. , 0.3, 0.3],
       [0.1, 0.1, 0.3, 1. , 0.5],
       [0.1, 0.1, 0.3, 0.5, 1. ]])

In [40]:
s1 = s(w1, 2)
s2 = s(w2, 2)

In [33]:
p1 = p(w1)


In [15]:
p2 = p(w2)

In [34]:
p1

array([[0.5       , 0.25      , 0.15      , 0.05      , 0.05      ],
       [0.22727273, 0.5       , 0.18181818, 0.04545455, 0.04545455],
       [0.11538462, 0.15384615, 0.5       , 0.11538462, 0.11538462],
       [0.05      , 0.05      , 0.15      , 0.5       , 0.25      ],
       [0.05      , 0.05      , 0.15      , 0.25      , 0.5       ]])

In [17]:
p2

array([[0.5       , 0.11111111, 0.27777778, 0.05555556, 0.05555556],
       [0.14285714, 0.5       , 0.21428571, 0.07142857, 0.07142857],
       [0.17857143, 0.10714286, 0.5       , 0.10714286, 0.10714286],
       [0.05      , 0.05      , 0.15      , 0.5       , 0.25      ],
       [0.05      , 0.05      , 0.15      , 0.25      , 0.5       ]])

In [44]:
p1_2 = update_p(p1, s1)
p2_2 = update_p(p2, s2)

In [43]:
p1_2

array([[0.22222222, 0.02777778, 0.        , 0.        , 0.        ],
       [0.02525253, 0.22222222, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.25510204, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])

In [45]:
p2_2

array([[0.22222222, 0.        , 0.0308642 , 0.        , 0.        ],
       [0.        , 0.29585799, 0.        , 0.        , 0.        ],
       [0.01984127, 0.        , 0.22222222, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])

In [46]:
pc = (p2_2 + p1_2)/2

In [47]:
pc

array([[0.22222222, 0.01388889, 0.0154321 , 0.        , 0.        ],
       [0.01262626, 0.25904011, 0.        , 0.        , 0.        ],
       [0.00992063, 0.        , 0.23866213, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.22222222, 0.02777778],
       [0.        , 0.        , 0.        , 0.02777778, 0.22222222]])